version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1
    environment:
      POSTGRES_DB: reportapp
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
    volumes:
      - ./reportapp-data-host:/var/lib/postgresql/data

#TODO
#volumes:
#  reportapp-data:
